import '../sound_used_screen/widgets/sound_used_item_widget.dart';import 'controller/sound_used_controller.dart';import 'models/sound_used_item_model.dart';import 'package:flutter/material.dart';import 'package:shaga_chat/core/app_export.dart';import 'package:shaga_chat/widgets/app_bar/appbar_image.dart';import 'package:shaga_chat/widgets/app_bar/appbar_image_2.dart';import 'package:shaga_chat/widgets/app_bar/custom_app_bar.dart';import 'package:shaga_chat/widgets/custom_elevated_button.dart';import 'package:shaga_chat/widgets/custom_outlined_button.dart';class SoundUsedScreen extends GetWidget<SoundUsedController> {const SoundUsedScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftGray90003, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowleftone();}), actions: [AppbarImage2(svgPath: ImageConstant.imgCategoriesshare, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 10.v))]), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 19.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 11.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgImage140x140, height: 140.adaptSize, width: 140.adaptSize, radius: BorderRadius.circular(24.h)), Padding(padding: EdgeInsets.only(left: 22.h, top: 37.v, bottom: 24.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_shanon".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 31.v), Text("lbl_28_7m_like".tr, style: theme.textTheme.titleSmall)]))])), SizedBox(height: 30.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(height: 38.v, text: "lbl_chat".tr, margin: EdgeInsets.only(right: 4.h), buttonStyle: CustomButtonStyles.outlineCyan, buttonTextStyle: CustomTextStyles.titleSmallDeeporangeA400)), Expanded(child: CustomOutlinedButton(height: 38.v, text: "msg_add_to_favorites".tr, margin: EdgeInsets.only(left: 4.h), buttonStyle: CustomButtonStyles.outlineCyan, buttonTextStyle: CustomTextStyles.titleSmallDeeporangeA400))]), SizedBox(height: 19.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgEllipse60x60, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h)), Padding(padding: EdgeInsets.only(left: 20.h, top: 6.v, bottom: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_shanon2".tr, style: CustomTextStyles.titleMediumBold), SizedBox(height: 7.v), Text("msg_professional_singer".tr, style: theme.textTheme.titleSmall)])), Spacer(), CustomElevatedButton(height: 32.v, width: 73.h, text: "lbl_follow".tr, margin: EdgeInsets.symmetric(vertical: 14.v), buttonStyle: CustomButtonStyles.fillBlueTL8, buttonTextStyle: CustomTextStyles.titleSmallOnPrimary)]), SizedBox(height: 24.v), Divider(), SizedBox(height: 23.v), Expanded(child: Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 201.v, crossAxisCount: 3, mainAxisSpacing: 8.h, crossAxisSpacing: 8.h), physics: BouncingScrollPhysics(), itemCount: controller.soundUsedModelObj.value.soundUsedItemList.value.length, itemBuilder: (context, index) {SoundUsedItemModel model = controller.soundUsedModelObj.value.soundUsedItemList.value[index]; return SoundUsedItemWidget(model);})))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
