import '../messages_screen/widgets/listaubrey_one_item_widget.dart';import '../messages_screen/widgets/listtheresa_item_widget.dart';import 'controller/messages_controller.dart';import 'models/listaubrey_one_item_model.dart';import 'models/listtheresa_item_model.dart';import 'package:flutter/material.dart';import 'package:shaga_chat/core/app_export.dart';import 'package:shaga_chat/widgets/app_bar/appbar_image.dart';import 'package:shaga_chat/widgets/app_bar/appbar_image_2.dart';import 'package:shaga_chat/widgets/app_bar/appbar_subtitle.dart';import 'package:shaga_chat/widgets/app_bar/custom_app_bar.dart';import 'package:shaga_chat/widgets/custom_search_view.dart';class MessagesScreen extends GetWidget<MessagesController> {const MessagesScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftGray90003, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 14.v), onTap: () {onTapArrowleftone();}), title: AppbarSubtitle(text: "lbl_messages".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarImage2(svgPath: ImageConstant.imgIconlycurvedplus, margin: EdgeInsets.only(left: 24.h, top: 10.v, right: 14.h)), AppbarImage2(svgPath: ImageConstant.imgClock, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 38.h))]), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 19.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [CustomSearchView(controller: controller.searchController, hintText: "lbl_search".tr, prefix: Container(margin: EdgeInsets.fromLTRB(20.h, 18.v, 12.h, 18.v), child: CustomImageView(svgPath: ImageConstant.imgSearchGray400)), prefixConstraints: BoxConstraints(maxHeight: 56.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(svgPath: ImageConstant.imgVolumeDeepOrangeA400)), suffixConstraints: BoxConstraints(maxHeight: 56.v)), SizedBox(height: 26.v), Text("lbl_recently".tr, style: theme.textTheme.titleLarge), SizedBox(height: 126.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(top: 22.v, right: 12.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: controller.messagesModelObj.value.listaubreyOneItemList.value.length, itemBuilder: (context, index) {ListaubreyOneItemModel model = controller.messagesModelObj.value.listaubreyOneItemList.value[index]; return ListaubreyOneItemWidget(model);}))), SizedBox(height: 26.v), Text("lbl_messages".tr, style: theme.textTheme.titleLarge), SizedBox(height: 21.v), Expanded(child: Obx(() => ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: controller.messagesModelObj.value.listtheresaItemList.value.length, itemBuilder: (context, index) {ListtheresaItemModel model = controller.messagesModelObj.value.listtheresaItemList.value[index]; return ListtheresaItemWidget(model);})))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
