import '../find_friends_screen/widgets/listcategoriess_item_widget.dart';import '../find_friends_screen/widgets/listelanor_pera_item_widget.dart';import 'controller/find_friends_controller.dart';import 'models/listcategoriess_item_model.dart';import 'models/listelanor_pera_item_model.dart';import 'package:flutter/material.dart';import 'package:shaga_chat/core/app_export.dart';import 'package:shaga_chat/widgets/app_bar/appbar_image.dart';import 'package:shaga_chat/widgets/app_bar/appbar_image_2.dart';import 'package:shaga_chat/widgets/app_bar/appbar_subtitle.dart';import 'package:shaga_chat/widgets/app_bar/custom_app_bar.dart';import 'package:shaga_chat/widgets/custom_search_view.dart';class FindFriendsScreen extends GetWidget<FindFriendsController> {const FindFriendsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftGray90003, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowleftone();}), title: AppbarSubtitle(text: "lbl_find_friends".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarImage2(svgPath: ImageConstant.imgIconlycurvedscan, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 10.v))]), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 23.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomSearchView(controller: controller.searchController, hintText: "lbl_search".tr, prefix: Container(margin: EdgeInsets.fromLTRB(20.h, 18.v, 12.h, 18.v), child: CustomImageView(svgPath: ImageConstant.imgSearchGray400)), prefixConstraints: BoxConstraints(maxHeight: 56.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(svgPath: ImageConstant.imgVolumeDeepOrangeA400)), suffixConstraints: BoxConstraints(maxHeight: 56.v)), SizedBox(height: 24.v), Expanded(child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: controller.findFriendsModelObj.value.listcategoriessItemList.value.length, itemBuilder: (context, index) {ListcategoriessItemModel model = controller.findFriendsModelObj.value.listcategoriessItemList.value[index]; return ListcategoriessItemWidget(model);}))), SizedBox(height: 26.v), Text("msg_suggested_accounts".tr, style: theme.textTheme.titleLarge), SizedBox(height: 22.v), Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: controller.findFriendsModelObj.value.listelanorPeraItemList.value.length, itemBuilder: (context, index) {ListelanorPeraItemModel model = controller.findFriendsModelObj.value.listelanorPeraItemList.value[index]; return ListelanorPeraItemWidget(model);}))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
